/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * The 'User Capability Profile' schema generated by Agent 1 (Interviewer),
 * consumed by Agent 2 (Market Scout), and used by Agent 3 (Outreach Specialist).
 */
export interface UserCapabilityProfile {
  fullName: string;
  email: string;
  primary_stack: string[]; // Primary engineering technologies/frameworks
  deep_skills: string[]; // Specific deep abilities and technical competencies
  architectural_experience: string; // Summary of solved architecture problems, trade-offs, and design choices
  communication_style: string; // The observed communication mode (e.g., precise, collaborative, pragmatic, detail-oriented)
  ideal_roles: string[]; // High-yield roles/gigs matched to this developer
}

/**
 * Prioritized Match Listing produced by Agent 2 (Market Scout)
 */
export interface MatchRecommendation {
  roleId: string;
  title: string;
  companyName: string;
  matchScore: number; // 0 to 100
  whyYouMatch: string; // Contextual breakdown linking candidate insights to role
  alignmentHighlights: {
    skillOverlap: string[];
    insightCongruence: string; // Description of how candidate experience solves company problems
  };
}

